# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_lostattractor 57EDCBEDDE7ABA6B44377FF2B96725F36430B3D1
  - &server_node0 age1280687ck6e9xpxdgra5fmw36hyjrgspnl58t9zul7udmfvpq954qavrkpa
  - &server_node1 age1339dyz6nk7j7sseyjc075k6vrv5eerlt35c90gvl3jzzrdgc9yxqjse276
  - &server_node2 age196hur3e04flr9le0s6xlmlxvdaq07skvzf5y222kklhn4vrgr4vs28fmqd
  - &server_ec2 age1rape8ctdn7ukxshxfd0mklvdcj4f6cknlnm89t8gwt5uj7al9f3qdl7hkz
  - &server_lightsail age1p4328l7xdphm4re3nfpsr00dh230nnqe9wyt9j9hmk8exmwsa3qqnd7gfr
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - pgp:
      - *admin_lostattractor
      age:
      - *server_node0
      - *server_node1
      - *server_node2
      - *server_ec2
      - *server_lightsail